#include<iostream>
#include<iomanip>
using namespace std;

int main(){
	
	int num [] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127};
	cout << "__________________________________________________________________________"<<endl;
	//cout << setw(80) << "                                                                          "<<endl;
	cout  << "|Dec   Hex   Oct  Char  |Dec   Hex   Oct  Char   |Dec   Hex   Oct  Char  |"<<endl;
	cout  << "|" << num[0]  << "     " <<std::hex<<num[0] << "      " <<std::oct<<num[0]  << "      " <<std::dec<<static_cast<char>(num[0])  << "  |"  <<"" << num[42]  << "     " <<std::hex<<num[42] << "      " <<std::oct<<num[42]       << "      " <<std::dec<<static_cast<char>(num[42]) << "   |" << "" << num[84]  << "     " <<std::hex<<num[85] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[85]) << " |" <<endl;
	cout  << "|" << num[1]  << "     " <<std::hex<<num[1] << "      " <<std::oct<<num[1]  << "      " <<std::dec<<static_cast<char>(num[1])  << "  |"  <<"" << num[43]  << "     " <<std::hex<<num[43] << "      " <<std::oct<<num[43]       << "      " <<std::dec<<static_cast<char>(num[43]) << "   |" << "" << num[85]  << "     " <<std::hex<<num[85] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[86]) << " |" <<endl;
	cout  << "|" << num[2]  << "     " <<std::hex<<num[2] << "      " <<std::oct<<num[2]  << "      " <<std::dec<<static_cast<char>(num[2])  << "  |"  <<"" << num[44]  << "     " <<std::hex<<num[44] << "      " <<std::oct<<num[44]       << "      " <<std::dec<<static_cast<char>(num[44]) << "   |" << "" << num[86]  << "     " <<std::hex<<num[86] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[87]) << " |" <<endl;
	cout  << "|" << num[3]  << "     " <<std::hex<<num[3] << "      " <<std::oct<<num[3]  << "      " <<std::dec<<static_cast<char>(num[3])  << "  |"  <<"" << num[45]  << "     " <<std::hex<<num[45] << "      " <<std::oct<<num[45]       << "      " <<std::dec<<static_cast<char>(num[45]) << "   |" << "" << num[87]  << "     " <<std::hex<<num[87] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[88]) << " |" <<endl;
	cout  << "|" << num[4]  << "     " <<std::hex<<num[4] << "      " <<std::oct<<num[4]  << "      " <<std::dec<<static_cast<char>(num[4])  << "  |"  <<"" << num[46]  << "     " <<std::hex<<num[46] << "      " <<std::oct<<num[46]       << "      " <<std::dec<<static_cast<char>(num[46]) << "   |" << "" << num[88]  << "     " <<std::hex<<num[88] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[89]) << " |" <<endl;
	cout  << "|" << num[5]  << "     " <<std::hex<<num[5] << "      " <<std::oct<<num[5]  << "      " <<std::dec<<static_cast<char>(num[5])  << "  |"  <<"" << num[47]  << "     " <<std::hex<<num[47] << "      " <<std::oct<<num[47]       << "      " <<std::dec<<static_cast<char>(num[47]) << "   |" << "" << num[89]  << "     " <<std::hex<<num[89] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[100])<< " |" <<endl;
	cout  << "|" << num[6]  << "     " <<std::hex<<num[6] << "      " <<std::oct<<num[6]  << "      " <<std::dec<<static_cast<char>(num[6])  << "  |"  <<"" << num[48]  << "     " <<std::hex<<num[48] << "      " <<std::oct<<num[48]       << "      " <<std::dec<<static_cast<char>(num[48]) << "   |" << "" << num[90]  << "     " <<std::hex<<num[90] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[101])<< " |" <<endl;
	cout  << "|" << num[7]  << "     " <<std::hex<<num[7] << "      " <<std::oct<<num[7]  << "      " <<std::dec<<static_cast<char>(num[7])  << "  |"  <<"" << num[49]  << "     " <<std::hex<<num[49] << "      " <<std::oct<<num[49]       << "      " <<std::dec<<static_cast<char>(num[49]) << "   |" << "" << num[91]  << "     " <<std::hex<<num[91] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[102])<< " |" <<endl;
	cout  << "|" << num[8]  << "     " <<std::hex<<num[8] << "      " <<std::oct<<num[8]  << "      " <<std::dec<<static_cast<char>(num[8])  << "  |"  <<"" << num[50]  << "     " <<std::hex<<num[50] << "      " <<std::oct<<num[50]       << "      " <<std::dec<<static_cast<char>(num[50]) << "   |" << "" << num[92]  << "     " <<std::hex<<num[92] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[103])<< " |" <<endl;
	cout  << "|" << num[9]  << "     " <<std::hex<<num[9] << "      " <<std::oct<<num[9]  << "      " <<std::dec<<static_cast<char>(num[9])  << "  |"  <<"" << num[51]  << "     " <<std::hex<<num[51] << "      " <<std::oct<<num[51]       << "      " <<std::dec<<static_cast<char>(num[51]) << "   |" << "" << num[93]  << "     " <<std::hex<<num[93] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[10] << "     " <<std::hex<<num[10]<< "      " <<std::oct<<num[10] << "      " <<std::dec<<static_cast<char>(num[10]) << "  |"  <<"" << num[52]  << "     " <<std::hex<<num[52] << "      " <<std::oct<<num[52]       << "      " <<std::dec<<static_cast<char>(num[52]) << "   |" << "" << num[94]  << "     " <<std::hex<<num[94] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[11] << "     " <<std::hex<<num[11]<< "      " <<std::oct<<num[11] << "      " <<std::dec<<static_cast<char>(num[11]) << "  |"  <<"" << num[53]  << "     " <<std::hex<<num[53] << "      " <<std::oct<<num[53]       << "      " <<std::dec<<static_cast<char>(num[53]) << "   |" << "" << num[95]  << "     " <<std::hex<<num[95] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[12] << "     " <<std::hex<<num[12]<< "      " <<std::oct<<num[12] << "      " <<std::dec<<static_cast<char>(num[12]) << "  |"  <<"" << num[54]  << "     " <<std::hex<<num[54] << "      " <<std::oct<<num[54]       << "      " <<std::dec<<static_cast<char>(num[54]) << "   |" << "" << num[96]  << "     " <<std::hex<<num[96] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[13] << "     " <<std::hex<<num[13]<< "      " <<std::oct<<num[13] << "      " <<std::dec<<static_cast<char>(num[13]) << "  |"  <<"" << num[55]  << "     " <<std::hex<<num[55] << "      " <<std::oct<<num[55]       << "      " <<std::dec<<static_cast<char>(num[55]) << "   |" << "" << num[97]  << "     " <<std::hex<<num[97] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[14] << "     " <<std::hex<<num[14]<< "      " <<std::oct<<num[14] << "      " <<std::dec<<static_cast<char>(num[14]) << "  |"  <<"" << num[56]  << "     " <<std::hex<<num[56] << "      " <<std::oct<<num[56]       << "      " <<std::dec<<static_cast<char>(num[56]) << "   |" << "" << num[98]  << "     " <<std::hex<<num[98] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[15] << "     " <<std::hex<<num[15]<< "      " <<std::oct<<num[15] << "      " <<std::dec<<static_cast<char>(num[15]) << "  |"  <<"" << num[57]  << "     " <<std::hex<<num[57] << "      " <<std::oct<<num[57]       << "      " <<std::dec<<static_cast<char>(num[57]) << "   |" << "" << num[99]  << "     " <<std::hex<<num[99] << "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[16] << "     " <<std::hex<<num[16]<< "      " <<std::oct<<num[16] << "      " <<std::dec<<static_cast<char>(num[16]) << "  |"  <<"" << num[58]  << "     " <<std::hex<<num[58] << "      " <<std::oct<<num[58]       << "      " <<std::dec<<static_cast<char>(num[58]) << "   |" << "" << num[100] << "     " <<std::hex<<num[100]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[17] << "     " <<std::hex<<num[17]<< "      " <<std::oct<<num[17] << "      " <<std::dec<<static_cast<char>(num[17]) << "  |"  <<"" << num[59]  << "     " <<std::hex<<num[59] << "      " <<std::oct<<num[59]       << "      " <<std::dec<<static_cast<char>(num[59]) << "   |" << "" << num[101] << "     " <<std::hex<<num[101]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[18] << "     " <<std::hex<<num[18]<< "      " <<std::oct<<num[18] << "      " <<std::dec<<static_cast<char>(num[18]) << "  |"  <<"" << num[60]  << "     " <<std::hex<<num[60] << "      " <<std::oct<<num[60]       << "      " <<std::dec<<static_cast<char>(num[60]) << "   |" << "" << num[102] << "     " <<std::hex<<num[102]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[19] << "     " <<std::hex<<num[19]<< "      " <<std::oct<<num[19] << "      " <<std::dec<<static_cast<char>(num[19]) << "  |"  <<"" << num[61]  << "     " <<std::hex<<num[61] << "      " <<std::oct<<num[61]       << "      " <<std::dec<<static_cast<char>(num[61]) << "   |" << "" << num[103] << "     " <<std::hex<<num[103]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[20] << "     " <<std::hex<<num[20]<< "      " <<std::oct<<num[20] << "      " <<std::dec<<static_cast<char>(num[20]) << "  |"  <<"" << num[62]  << "     " <<std::hex<<num[62] << "      " <<std::oct<<num[62]       << "      " <<std::dec<<static_cast<char>(num[62]) << "   |" << "" << num[104] << "     " <<std::hex<<num[104]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[21] << "     " <<std::hex<<num[21]<< "      " <<std::oct<<num[21] << "      " <<std::dec<<static_cast<char>(num[21]) << "  |"  <<"" << num[63]  << "     " <<std::hex<<num[63] << "      " <<std::oct<<num[63]       << "      " <<std::dec<<static_cast<char>(num[63]) << "   |" << "" << num[105] << "     " <<std::hex<<num[105]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[22] << "     " <<std::hex<<num[22]<< "      " <<std::oct<<num[22] << "      " <<std::dec<<static_cast<char>(num[22]) << "  |"  <<"" << num[64]  << "     " <<std::hex<<num[64] << "      " <<std::oct<<num[64]       << "      " <<std::dec<<static_cast<char>(num[64]) << "   |" << "" << num[106] << "     " <<std::hex<<num[106]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[23] << "     " <<std::hex<<num[23]<< "      " <<std::oct<<num[23] << "      " <<std::dec<<static_cast<char>(num[23]) << "  |"  <<"" << num[65]  << "     " <<std::hex<<num[65] << "      " <<std::oct<<num[65]       << "      " <<std::dec<<static_cast<char>(num[65]) << "   |" << "" << num[107] << "     " <<std::hex<<num[107]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[24] << "     " <<std::hex<<num[24]<< "      " <<std::oct<<num[24] << "      " <<std::dec<<static_cast<char>(num[24]) << "  |"  <<"" << num[66]  << "     " <<std::hex<<num[66] << "      " <<std::oct<<num[66]       << "      " <<std::dec<<static_cast<char>(num[66]) << "   |" << "" << num[108] << "     " <<std::hex<<num[108]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[25] << "     " <<std::hex<<num[25]<< "      " <<std::oct<<num[25] << "      " <<std::dec<<static_cast<char>(num[25]) << "  |"  <<"" << num[67]  << "     " <<std::hex<<num[67] << "      " <<std::oct<<num[67]       << "      " <<std::dec<<static_cast<char>(num[67]) << "   |" << "" << num[109] << "     " <<std::hex<<num[109]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[26] << "     " <<std::hex<<num[26]<< "      " <<std::oct<<num[26] << "      " <<std::dec<<static_cast<char>(num[26]) << "  |"  <<"" << num[68]  << "     " <<std::hex<<num[68] << "      " <<std::oct<<num[68]       << "      " <<std::dec<<static_cast<char>(num[68]) << "   |" << "" << num[110] << "     " <<std::hex<<num[110]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[27] << "     " <<std::hex<<num[27]<< "      " <<std::oct<<num[27] << "      " <<std::dec<<static_cast<char>(num[27]) << "  |"  <<"" << num[69]  << "     " <<std::hex<<num[69] << "      " <<std::oct<<num[69]       << "      " <<std::dec<<static_cast<char>(num[69]) << "   |" << "" << num[111] << "     " <<std::hex<<num[111]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[28] << "     " <<std::hex<<num[28]<< "      " <<std::oct<<num[28] << "      " <<std::dec<<static_cast<char>(num[28]) << "  |"  <<"" << num[70]  << "     " <<std::hex<<num[70] << "      " <<std::oct<<num[70]       << "      " <<std::dec<<static_cast<char>(num[70]) << "   |" << "" << num[112] << "     " <<std::hex<<num[112]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[29] << "     " <<std::hex<<num[29]<< "      " <<std::oct<<num[29] << "      " <<std::dec<<static_cast<char>(num[29]) << "  |"  <<"" << num[71]  << "     " <<std::hex<<num[71] << "      " <<std::oct<<num[71]       << "      " <<std::dec<<static_cast<char>(num[71]) << "   |" << "" << num[113] << "     " <<std::hex<<num[113]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[30] << "     " <<std::hex<<num[30]<< "      " <<std::oct<<num[30] << "      " <<std::dec<<static_cast<char>(num[30]) << "  |"  <<"" << num[72]  << "     " <<std::hex<<num[72] << "      " <<std::oct<<num[72]       << "      " <<std::dec<<static_cast<char>(num[72]) << "   |" << "" << num[114] << "     " <<std::hex<<num[114]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[31] << "     " <<std::hex<<num[31]<< "      " <<std::oct<<num[31] << "      " <<std::dec<<static_cast<char>(num[31]) << "  |"  <<"" << num[73]  << "     " <<std::hex<<num[73] << "      " <<std::oct<<num[73]       << "      " <<std::dec<<static_cast<char>(num[73]) << "   |" << "" << num[115] << "     " <<std::hex<<num[115]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[32] << "     " <<std::hex<<num[32]<< "      " <<std::oct<<num[32] << "      " <<std::dec<<static_cast<char>(num[32]) << "  |"  <<"" << num[74]  << "     " <<std::hex<<num[74] << "      " <<std::oct<<num[74]       << "      " <<std::dec<<static_cast<char>(num[74]) << "   |" << "" << num[116] << "     " <<std::hex<<num[116]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[33] << "     " <<std::hex<<num[33]<< "      " <<std::oct<<num[33] << "      " <<std::dec<<static_cast<char>(num[33]) << "  |"  <<"" << num[75]  << "     " <<std::hex<<num[75] << "      " <<std::oct<<num[75]       << "      " <<std::dec<<static_cast<char>(num[75]) << "   |" << "" << num[117] << "     " <<std::hex<<num[117]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[34] << "     " <<std::hex<<num[34]<< "      " <<std::oct<<num[34] << "      " <<std::dec<<static_cast<char>(num[34]) << "  |"  <<"" << num[76]  << "     " <<std::hex<<num[76] << "      " <<std::oct<<num[76]       << "      " <<std::dec<<static_cast<char>(num[76]) << "   |" << "" << num[118] << "     " <<std::hex<<num[118]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[35] << "     " <<std::hex<<num[35]<< "      " <<std::oct<<num[35] << "      " <<std::dec<<static_cast<char>(num[35]) << "  |"  <<"" << num[77]  << "     " <<std::hex<<num[77] << "      " <<std::oct<<num[77]       << "      " <<std::dec<<static_cast<char>(num[77]) << "   |" << "" << num[119] << "     " <<std::hex<<num[119]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[36] << "     " <<std::hex<<num[36]<< "      " <<std::oct<<num[36] << "      " <<std::dec<<static_cast<char>(num[36]) << "  |"  <<"" << num[78]  << "     " <<std::hex<<num[78] << "      " <<std::oct<<num[78]       << "      " <<std::dec<<static_cast<char>(num[78]) << "   |" << "" << num[120] << "     " <<std::hex<<num[120]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[37] << "     " <<std::hex<<num[37]<< "      " <<std::oct<<num[37] << "      " <<std::dec<<static_cast<char>(num[37]) << "  |"  <<"" << num[79]  << "     " <<std::hex<<num[79] << "      " <<std::oct<<num[79]       << "      " <<std::dec<<static_cast<char>(num[79]) << "   |" << "" << num[121] << "     " <<std::hex<<num[121]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[38] << "     " <<std::hex<<num[38]<< "      " <<std::oct<<num[38] << "      " <<std::dec<<static_cast<char>(num[38]) << "  |"  <<"" << num[80]  << "     " <<std::hex<<num[80] << "      " <<std::oct<<num[80]       << "      " <<std::dec<<static_cast<char>(num[80]) << "   |" << "" << num[122] << "     " <<std::hex<<num[122]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[39] << "     " <<std::hex<<num[39]<< "      " <<std::oct<<num[39] << "      " <<std::dec<<static_cast<char>(num[39]) << "  |"  <<"" << num[81]  << "     " <<std::hex<<num[81] << "      " <<std::oct<<num[81]       << "      " <<std::dec<<static_cast<char>(num[81]) << "   |" << "" << num[123] << "     " <<std::hex<<num[123]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[40] << "     " <<std::hex<<num[40]<< "      " <<std::oct<<num[40] << "      " <<std::dec<<static_cast<char>(num[40]) << "  |"  <<"" << num[82]  << "     " <<std::hex<<num[82] << "      " <<std::oct<<num[82]       << "      " <<std::dec<<static_cast<char>(num[82]) << "   |" << "" << num[124] << "     " <<std::hex<<num[124]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
	cout  << "|" << num[41] << "     " <<std::hex<<num[41]<< "      " <<std::oct<<num[41] << "      " <<std::dec<<static_cast<char>(num[41]) << "  |"  <<"" << num[83]  << "     " <<std::hex<<num[83] << "      " <<std::oct<<num[83]       << "      " <<std::dec<<static_cast<char>(num[83]) << "   |" << "" << num[125] << "     " <<std::hex<<num[125]<< "      " <<std::oct<<num[0] << "      " <<std::dec<<static_cast<char>(num[0])  << " |" <<endl;
}  
